version: '3'

services:
  house_db:
    image: postgres
    container_name: house_db
  web:
    build: .
    command: bash -c "sleep 10 &&
                      python manage.py migrate &&
                      python manage.py loaddata dump.json &&
                      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - house_db
