# Generated by Django 2.0.7 on 2018-07-19 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('st_number', models.CharField(max_length=255)),
                ('apartment_amount', models.CharField(max_length=255)),
                ('build_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Housemates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('apartment', models.CharField(max_length=255)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.House')),
            ],
        ),
    ]
